# Shell variables
# Generated by 'wal'
wallpaper='/home/lazarus/.config/wpg/wallpapers/photo-1496065187959-7f07b8353c55.jpeg'

# Special
background='#0f0f0f'
foreground='#e3cade'
cursor='#e3cade'

# Colors
color0='#0f0f0f'
color1='#A32B42'
color2='#4D4EA2'
color3='#6154A8'
color4='#A367AE'
color5='#8083C9'
color6='#A394D4'
color7='#e3cade'
color8='#9e8d9b'
color9='#A32B42'
color10='#4D4EA2'
color11='#6154A8'
color12='#A367AE'
color13='#8083C9'
color14='#A394D4'
color15='#e3cade'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
