# Shell variables
# Generated by 'wal'
wallpaper='/home/lazarus/.config/wpg/wallpapers/1518902452975.png'

# Special
background='#150e14'
foreground='#e9e2de'
cursor='#e9e2de'

# Colors
color0='#150e14'
color1='#DA4F4F'
color2='#D76567'
color3='#9B837B'
color4='#B8A59C'
color5='#C6B3A9'
color6='#D7C8B8'
color7='#e9e2de'
color8='#a39e9b'
color9='#DA4F4F'
color10='#D76567'
color11='#9B837B'
color12='#B8A59C'
color13='#C6B3A9'
color14='#D7C8B8'
color15='#e9e2de'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
