# Shell variables
# Generated by 'wal'
wallpaper='/home/lazarus/.config/wpg/wallpapers/shin_godzilla.jpg'

# Special
background='#050506'
foreground='#fff4f5'
cursor='#f2dfe0'

# Colors
color0='#050506'
color1='#E5242B'
color2='#BC4248'
color3='#DA5C62'
color4='#D37D82'
color5='#EA9EA2'
color6='#E1B2B5'
color7='#f2dfe0'
color8='#16161c'
color9='#ff1d27'
color10='#ff454e'
color11='#ff636d'
color12='#ff8c95'
color13='#ffb3bb'
color14='#ffc7ce'
color15='#fff4f5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
