# Shell variables
# Generated by 'wal'
wallpaper='/home/void/.config/wpg/wallpapers/erez-attias-58871-unsplash.jpg'

# Special
background='#1c1f1f'
foreground='#c6c7c7'
cursor='#c6c7c7'

# Colors
color0='#1c1f1f'
color1='#0f596e'
color2='#635246'
color3='#247986'
color4='#7c6758'
color5='#817f80'
color6='#b1988e'
color7='#c6c7c7'
color8='#545757'
color9='#0f596e'
color10='#635246'
color11='#247986'
color12='#7c6758'
color13='#817f80'
color14='#b1988e'
color15='#c6c7c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="$LS_COLORS:su=30;41:ow=30;42:st=30;44:"
